#!/bin/sh

GITHUB_REPO='node-cache'
SUBDIR='node_modules'

V="${V-0}" # default to friendly messages

set -eu
cd "$(realpath -m "$0"/../..)"
. tools/git-utils.sh

cmd_remove() {
    # if we did this for ourselves the rm is enough, but it might be the case
    # that someone actually used git-submodule to fetch this, so clean up after
    # that as well.  NB: deinit nicely recreates the empty directory for us.
    message REMOVE node_modules
    rm -rf node_modules
    git submodule deinit node_modules
    rm -rf -- "$(git rev-parse --absolute-git-dir)/modules/node_modules"
}

cmd_checkout() {
    # we default to check out the node_modules corresponding to the gitlink in the index
    local sha="${1-$(get_index_gitlink node_modules)}"

    # fetch by sha to prevent us from downloading something we don't want
    fetch_sha_to_cache "${sha}"

    # verify that our package.json is equal to the one the cached node_modules
    # was created with, unless --force is given
    if [ "${1-}" != "--force" ]; then
        if ! cmp_from_cache "${sha}" '.package.json' 'package.json'; then
            cat >&2 <<EOF

*** node_modules ${sha} doesn't match our package.json
*** refusing to automatically check out node_modules

Options:

    - tools/node-modules checkout --force     # disable this check

    - tools/node-modules install              # npm install with our package.json

$0: *** aborting

EOF
            exit 1
        fi
    fi

    # we're actually going to do this; let's remove the old one
    cmd_remove

    # and check out the new one
    # we need to use the tag name here, unfortunately
    clone_from_cache "${sha}"
}

cmd_npm_install() {
    # Lots of cockpit developers are using toolbox, which can't recursively run
    # podman, but flatpak-spawn offers a nice workaround for that.
    if [ -f /run/.toolboxenv ]; then
        exec flatpak-spawn --host -- "$0" npm_install "$@"
        exit 1
    fi

    CACHE="cockpit-project-npm-cache-volume"
    IMAGE="docker.io/library/node:alpine"

    # make sure the node user can write to the cache volume
    podman run \
        --rm \
        --volume "${CACHE}":/home/node/.npm:U \
        "${IMAGE}" chown -R node:node /home/node >&2

    # do the actual work
    exec podman run \
        --log-driver='none' \
        --rm \
        --init \
        --user node \
        --workdir /home/node \
        --interactive \
        --attach stdin \
        --attach stdout \
        --attach stderr \
        --volume "${CACHE}":/home/node/.npm \
        "${IMAGE}" /bin/sh -c '
            set -eux
            tee package.json >/dev/null
            # We background npm and wait for it: this allows the script to be terminated with ^C
            # Otherwise, termination would fail, because podman delivers the signal to the main
            # process (the shell) which ignores SIGINT until npm returns.  npm never see it.
            npm install --ignore-scripts >&2 & wait
            cp package.json node_modules/.package.json
            tar c node_modules
        '
}

cat_file() {
    case "$1" in
        *:*)
            git cat-file blob "$1";;
        *)
            cat "$1";;
    esac
}

tar_to_git() {
    tar --exclude '.git*' --extract "$1"
    message INDEX "node_modules"
    git -C "$1" init --quiet --initial-branch=main
    git -C "$1" add --all
}

cmd_install() {
    cmd_remove

    cmd_npm_install < package.json | tar_to_git node_modules

    # consistency check
    cmp package.json node_modules/.package.json
    ls -l node_modules/.package-lock.json >&2

    # commit
    git -C node_modules commit --quiet --message "$(sha256sum package.json)"

    sha="$(git -C node_modules rev-parse HEAD)"
    tag="sha-${sha}"
    message TAG "${tag}"
    git -C node_modules tag -f "${tag}" "${sha}"

    cat <<EOF
Next steps:

  - git add node_modules && git commit
  - tools/node-modules push

EOF
}

cmd_tree_hash() {
    rm -rf tmp/npm-tree-hash
    mkdir -p tmp/npm-tree-hash
    git cat-file blob "$1:package.json" | cmd_npm_install | (cd tmp/npm-tree-hash && tar_to_git node_modules)
    git -C tmp/npm-tree-hash/node_modules write-tree
}

cmd_push() {
    tag="sha-$(git -C node_modules rev-parse HEAD)"
    message PUSH "${GITHUB_REPO} ${tag}"
    git -C node_modules push "${SSH_REMOTE}" "${tag}"
}

# called from Makefile.am
cmd_make_package_lock_json() {
    # Run from make to ensure package-lock.json is up to date

    # package-lock.json is used as the stamp file for all things that use
    # node_modules (mostly webpack), so this is the main bit of glue that
    # drives the entire process

    # We try our best not to touch package-lock.json unless it actually changes

    # This isn't going to work for a tarball, but as long as
    # package-lock.json is already there, and newer than package.json,
    # we're OK
    if [ ! -e .git ]; then
        if [ package-lock.json -nt package.json ]; then
            exit 0
        fi

        echo "*** Can't update node modules unless running from git" >&2
        exit 1
    fi

    # Otherwise, our main goal is to ensure that the node_modules from
    # the index is the one that we actually have.
    local sha="$(get_index_gitlink node_modules)"
    if [ ! -e node_modules/.git ]; then
        # nothing there yet...
        cmd_checkout
    elif [ "$(git -C node_modules rev-parse HEAD)" != "${sha}" ]; then
        # wrong thing there...
        cmd_checkout
    fi

    # This check is more about catching local changes to package.json than
    # about validating something we just checked out:
    if ! cmp -s node_modules/.package.json package.json; then
        cat 2>&1 <<EOF
*** package.json is out of sync with node_modules
*** If you modified package.json, please run:
***
***    tools/node-modules install
***
*** and add the result to the index.
EOF
        exit 1
    fi

    # Only copy the package-lock.json if it differs from the one we have
    if ! cmp -s node_modules/.package-lock.json package-lock.json; then
        message COPY package-lock.json
        cp node_modules/.package-lock.json package-lock.json
    fi

    # We're now in a situation where:
    #  - the checked out node_modules is equal to the gitlink in the index
    #  - the package.json in the tree is equal to the one in node_modules
    #  - ditto package-lock.json
    exit 0
}

main() {
    local cmd="${1-}"

    if [ -z "${cmd}" ]; then
        # don't list the "private" ones
        echo 'This command requires a subcommand: remove checkout install push'
        exit 1
    elif ! type -t "cmd_${cmd}" | grep -q function; then
        echo "Unknown subcommand ${cmd}"
        exit 1
    fi

    shift
    [ -n "${quiet}" ] || set -x
    "cmd_$cmd" "$@"
}

main "$@"
